### ISSUE TITLE
Update readthedocs config to use `build.os` instead of `build.image`

### ISSUE THREAD

**Issue by ThalesCarl** [ESSS/alfasim-sdk#317]
* alfasim-sdk version: 0.17 (unreleased)
* Python version: 3.10
* Operating System: windows

### Description

While working on PR https://github.com/ESSS/alfasim-sdk/pull/316, the readthedocs failed with the following messsage:

```
The configuration key "build.image" is deprecated. Use "build.os" instead to continue building your project. 
Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os
```

From [this](https://blog.readthedocs.com/use-build-os-config/) readthedocs' announcement, we can see that we need to update the configuration of the project before October 16, 2023.

### What I Did

While working on the PR #316 I have changed the configuration as below
```yaml
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.7"

python:
    install:
        -   method: pip
            path: .
        -   requirements: docs/requirements.txt
sphinx:
    configuration: docs/source/conf.py
    fail_on_warning: true
```
It succeed the building, but I am not sure if this is the best approach for the newer version of the readthedocs. Furthermore, the following warning was thrown:

```
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
```

Since our policy is to `fail_on_warning`, then this must be correct as well in this issue.
